name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup msbuild
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Nuget restore
      run: nuget restore HSPI_DeviceCompare.sln
      
    - name: MSBuild
      run: |
        msbuild /p:Configuration=Debug HSPI_DeviceCompare.sln
        msbuild /p:Configuration=Release HSPI_DeviceCompare.sln
        
    - name: Stage artifacts
      run: |
        mkdir artifacts
        cp HSPI_DeviceCompare\bin\Release\HSPI_DeviceCompare.exe artifacts\HSPI_DeviceCompare.exe
        mkdir "artifacts\Debug Build"
        cp HSPI_DeviceCompare\bin\Debug\HSPI_DeviceCompare.exe "artifacts\Debug Build\HSPI_DeviceCompare.exe"
        echo %GITHUB_SHA% > artifacts\CommitHash.txt
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Plugin
        path: artifacts
