name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: MSBuild
      working-directory: src
      run: |
        msbuild /p:Configuration=Debug %GITHUB_WORKSPACE%
        msbuild /p:Configuration=Release %GITHUB_WORKSPACE%
